### ISSUE TITLE
Make middle panel wider in CSS & add code for image ZOOM

### ISSUE THREAD

**Issue by MonikaBarget** [ieg-dhr/DigiKAR_Projektseminar#2]
<style>
.zoom {
  padding: 50px;
  background-color: green;
  transition: transform .2s; /* Animation */
  width: 200px;
  height: 200px;
  margin: 0 auto;
}

.zoom:hover {
  transform: scale(1.5); /* (150% zoom - Note: if the zoom is too large, it will go outside of the viewport) */
}
</style>

**Comment by fabiancremer** [comment]
solved with scss
